#!/usr/bin/env bash
# Prepare this checkout to run on a server. Idempotent: safe to re-run, and it
# never overwrites an existing .env.
#
#   ./install.sh              check prerequisites, create .env files, generate secrets
#   ./install.sh --start      also bring the gateway up
#   ./install.sh --check      prerequisites only, change nothing
#
# It deliberately does NOT: join the tailnet, apply the policy, or create
# anything that costs money. Those are decisions, not installation steps, and
# docs/devops-setup.md walks them in the order that matters.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO_ROOT"

ok()   { printf '  \033[32mok\033[0m    %s\n' "$*"; }
warn() { printf '  \033[33mwarn\033[0m  %s\n' "$*"; }
bad()  { printf '  \033[31mFAIL\033[0m  %s\n' "$*"; FAILED=1; }
head_(){ printf '\n\033[1m%s\033[0m\n' "$*"; }

FAILED=0
MODE=setup
case "${1:-}" in
  --start) MODE=start ;;
  --check) MODE=check ;;
  "")      ;;
  *)       echo "unknown argument: $1" >&2; exit 2 ;;
esac

# ------------------------------------------------------------ prerequisites

head_ "Prerequisites"

for c in docker python3 openssl curl; do
  if command -v "$c" >/dev/null 2>&1; then ok "$c"; else bad "$c not found"; fi
done

if docker compose version >/dev/null 2>&1; then
  ok "docker compose (v2)"
else
  bad "docker compose v2 not available — 'docker-compose' v1 is not supported"
fi

if docker info >/dev/null 2>&1; then
  ok "docker daemon reachable"
else
  bad "cannot talk to the docker daemon — is it running, and is this user in the docker group?"
fi

# Not fatal: the gateway runs without it, but nothing can reach the gateway
# until the host is on the tailnet.
if command -v tailscale >/dev/null 2>&1; then
  if tailscale status >/dev/null 2>&1; then ok "tailscale up"
  else warn "tailscale installed but not connected — docs/devops-setup.md §3"; fi
else
  warn "tailscale not installed — the gateway will run but nothing can reach it"
fi

# The gateway is a long-running service; on a server it should survive reboot.
if [ "$(uname -s)" = Linux ] && command -v systemctl >/dev/null 2>&1; then
  if systemctl is-enabled docker >/dev/null 2>&1; then ok "docker enabled at boot"
  else warn "docker is not enabled at boot — 'sudo systemctl enable docker', or the gateway will not come back after a reboot"; fi
fi

[ "$FAILED" = 1 ] && { printf '\nFix the failures above, then re-run.\n'; exit 1; }
[ "$MODE" = check ] && { printf '\nPrerequisites only — nothing changed.\n'; exit 0; }

# ------------------------------------------------------------ configuration

head_ "Configuration"

# Every secret is generated here rather than typed, and the file is created 0600
# before anything is written into it — not chmod'ed afterwards, which would
# leave a window where the secrets are world-readable.
gen() { openssl rand -hex 24; }

if [ -f gateway/.env ]; then
  ok "gateway/.env exists (left untouched)"
else
  ( umask 077; cat > gateway/.env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# LITELLM_MASTER_KEY must start with sk- or LiteLLM rejects it at boot.
LITELLM_MASTER_KEY=sk-$(gen)
LITELLM_DB_PASS=$(gen)
ENGINE_SECRET=$(gen)
UI_USERNAME=admin
UI_PASSWORD=$(gen)
BACKUP_PASSPHRASE=$(gen)
# Filled in once the GPU node exists — docs/devops-setup.md §4.4.
# A placeholder is the correct state until then: the gateway answers a clear
# 503 rather than failing obscurely.
ENGINE_API_BASE=http://gpu.example.ts.net:8000/v1
EOF
  )
  ok "gateway/.env created, 0600, all secrets generated"
  warn "BACKUP_PASSPHRASE is in there — copy it to your password manager NOW. Lose it and every encrypted dump is scrap."
fi

if [ -f scripts/.env ]; then
  ok "scripts/.env exists (left untouched)"
else
  ( umask 077; cp scripts/.env.example scripts/.env )
  ok "scripts/.env created from the template, 0600"
  warn "fill in GPU_PROVIDER and its credentials before running gpu-up.sh"
fi

chmod 600 gateway/.env scripts/.env
mkdir -p backups && chmod 700 backups
ok "backups/ present, 0700"

# ------------------------------------------------------------ start

if [ "$MODE" = start ]; then
  head_ "Starting the gateway"
  ( cd gateway && docker compose up -d )
  ok "gateway up"
  printf '\n'
  ./verify.sh || true
fi

# ------------------------------------------------------------ next

head_ "Next"
cat <<'EOF'
  1. docs/devops-setup.md  — tailnet policy, gateway node, serve, GPU node,
                             in the order that matters (tags are checked at
                             registration, so the order is not cosmetic)
  2. scripts/.env          — pick GPU_PROVIDER: runpod | ssh | manual
                             (scripts/providers/README.md)
  3. cd gateway && docker compose up -d
  4. ./verify.sh --disruptive

  Cost guards and backups, once a provider is configured:
     cd gateway && TZ=Your/Zone docker compose --profile scheduler up -d
EOF
